version: '3.7'

services:
  app:
    build: .
    container_name: server
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src
    networks:
       - hackaton-caixa

networks:
    hackaton-caixa: